# This CI/CD template is to trigger a configuration push to Nginx Instance Manager when changes are introduced in the config files for an instance or instance group.
# The required variables are IP and authorization token of the Nginx Instance Manager. Please modify as needed for your project needs.


stages:
  - publish

variables:
  # Please provide variables specifically needed to connect to your Nginx Instance Manager
  # NOTE: your image must have bash as the default shell
  # You can find the specifications needed for base image is in the dockerfile

  BUILD_IMAGE: ${BASE_IMAGE}
  # IP of your Nginx Instance Manager
  CTRL_IP: 34.213.65.152
  # Authorization token to send API requests to Nginx Instance Manager
  AUTH_TOKEN: YWRtaW46VGVzdGVudjEyIw==
  # System UID of the instance
  SYSTEM_UID: fbf7a63f-a394-34b7-8775-93d7d6aceb82
  # Nginx UID of the instance
  NGINX_UID: 98961494-c999-515c-ae1b-1dd949f78b6e
  # Instance group UID
  GROUP_UID: 0ba1d2c3-ce36-44da-a786-94fb65425a30

._run_only_when_change_in_instance_directory: &_run_only_when_change_in_instance_directory
  changes:
    - instance/nginx.conf
    - instance/*

publish-config-to-instance:
  image: ${BUILD_IMAGE}
  stage: publish
  script:
    # Run the script that prepares the payload with config changes with required variables
    # - ./prepare-payload.sh ${CTRL_IP} ${AUTH_TOKEN} ${SYSTEM_UID} ${NGINX_UID}
  only:
    <<: *_run_only_when_change_in_instance_directory
  needs: []


._run_only_when_change_in_instance_group_directory: &_run_only_when_change_in_instance_group_directory
  changes:
    - instance-group/nginx.conf
    - instance-group/*

publish-config-to-instance-group:
  image: ${BUILD_IMAGE}
  stage: publish
  script:
    # Run the script that prepares the payload with config changes with required variables
    # - ./prepare-instGroup-payload.sh ${CTRL_IP} ${AUTH_TOKEN} ${GROUP_UID}
  only:
    <<: *_run_only_when_change_in_instance_group_directory
  needs: []