# This CI/CD template is to trigger a configuration push to Nginx Instance Manager when changes are introduced in the config files for an instance or instance group.
# The required variables are IP and authorization token of the Nginx Instance Manager. Please modify as needed for your project needs.


stages:
  - publish

variables:
  # Please provide variables specifically needed to connect to your Nginx Instance Manager
  # NOTE: your image must have bash as the default shell
  # You can find the specifications needed for base image is in the dockerfile

  BUILD_IMAGE: ${BASE_IMAGE}
  # IP of your Nginx Instance Manager
  CTRL_IP: 20.254.65.35
  # Authorization token to send API requests to Nginx Instance Manager
  AUTH_TOKEN: YWRtaW46amNVcFFNNlFPQ3pKTWU0aXZSY0VWa2Q1NGdTTElL
  # System UID of the instance
  SYSTEM_UID: c0d4564c-3c11-3eb7-b977-5a564a9e31a0
  # Nginx UID of the instance
  NGINX_UID: 6df3f8f6-0731-5478-b495-f364d3ee1230
  # Instance group UID
  GROUP_UID: 833d000d-295b-5a0c-b1a6-90b54a9acb71

._run_only_when_change_in_instance_directory: &_run_only_when_change_in_instance_directory
  changes:
    - instance/nginx.conf
    - instance/*

publish-config-to-instance:
  image: ${BUILD_IMAGE}
  stage: publish
  script:
    # Run the script that prepares the payload with config changes with required variables
    # - ./prepare-payload.sh ${CTRL_IP} ${AUTH_TOKEN} ${SYSTEM_UID} ${NGINX_UID}
    # - ./prepare-payload.sh 20.254.65.35 WRtaW46amNVcFFNNlFPQ3pKTWU0aXZSY0VWa2Q1NGdTTElL c0d4564c-3c11-3eb7-b977-5a564a9e31a0 6df3f8f6-0731-5478-b495-f364d3ee1230
  only:
    <<: *_run_only_when_change_in_instance_directory
  needs: []


._run_only_when_change_in_instance_group_directory: &_run_only_when_change_in_instance_group_directory
  changes:
    - instance-group/nginx.conf
    - instance-group/*

publish-config-to-instance-group:
  image: ${BUILD_IMAGE}
  stage: publish
  script:
    # Run the script that prepares the payload with config changes with required variables
    # - ./prepare-instGroup-payload.sh ${CTRL_IP} ${AUTH_TOKEN} ${GROUP_UID}
  only:
    <<: *_run_only_when_change_in_instance_group_directory
  needs: []